#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Noyalib
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Per-function complexity ceilings, enforced against a committed
# baseline that may only shrink.
#
# Clippy measures two of the ceilings the repository standard sets:
# lines per function (`too_many_lines`, ceiling 60) and SonarSource
# cognitive complexity (`cognitive_complexity`, ceiling 15). The
# thresholds live in scripts/complexity/clippy.toml and are applied
# through CLIPPY_CONF_DIR, so the ordinary clippy run keeps its own
# configuration. Cyclomatic complexity and Halstead difficulty are not
# measured here: clippy has no lint for them.
#
# The baseline (scripts/complexity/baseline.tsv) lists every function
# over a ceiling today, with its measured value. Check mode fails when
# a function joins the list or grows; it also fails when the list has
# improved but the baseline was not regenerated, so the file always
# states the truth. Update mode regenerates the file and refuses to
# record a regression.
#
# Usage:
#   scripts/complexity-baseline.sh            check against the baseline
#   scripts/complexity-baseline.sh --update   record an improvement
#   scripts/complexity-baseline.sh --from-json FILE [--baseline FILE]
#                                             read clippy JSON from FILE
#                                             (self-tests; no cargo run)
#
# Exit status: 0 clean, 1 regression, 2 baseline stale (run --update),
# 64 usage.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

CONF_DIR="$PWD/scripts/complexity"
BASELINE="$CONF_DIR/baseline.tsv"
MODE=check
JSON_IN=""

usage() {
  sed -n '/^# Usage:/,/^# Exit status/p' "$0" | sed 's/^# \{0,1\}//'
  exit 64
}

while [ $# -gt 0 ]; do
  case "$1" in
    --update) MODE=update ;;
    --from-json) shift; JSON_IN=${1:-}; [ -n "$JSON_IN" ] || usage ;;
    --baseline) shift; BASELINE=${1:-}; [ -n "$BASELINE" ] || usage ;;
    -h | --help) usage ;;
    *) echo "unknown argument: $1" >&2; usage ;;
  esac
  shift
done

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# measure: run clippy with the gate's thresholds and both lints forced
# to warn. Command-line levels win over the manifest's `allow`, and
# the separate target dir keeps this run out of the main clippy cache.
measure() {
  if [ -n "$JSON_IN" ]; then
    cat "$JSON_IN"
    return
  fi
  CLIPPY_CONF_DIR="$CONF_DIR" cargo clippy --workspace --all-targets --locked \
    --target-dir target/complexity --message-format=json --quiet -- \
    -W clippy::too_many_lines -W clippy::cognitive_complexity
}

# rows: one line per offending function, `lint<TAB>file<TAB>fn<TAB>value`,
# de-duplicated across targets (a lib function is reported once per
# target that compiles it) by keeping the largest measured value.
rows() {
  jq -r '
    select(.reason == "compiler-message") | .message
    | select(.code.code == "clippy::too_many_lines"
          or .code.code == "clippy::cognitive_complexity")
    | [.code.code, .spans[0].file_name, .spans[0].text[0].text, .message]
    | @tsv' \
  | awk -F'\t' '
      {
        name = "?"
        if (match($3, /fn[ \t]+[A-Za-z0-9_]+/)) {
          name = substr($3, RSTART, RLENGTH); sub(/^fn[ \t]+/, "", name)
        }
        value = 0
        if (match($4, /\([0-9]+\/[0-9]+\)/)) {
          value = substr($4, RSTART + 1, RLENGTH - 2); sub(/\/.*/, "", value)
        }
        sub(/^clippy::/, "", $1)
        key = $1 "\t" $2 "\t" name
        if (!(key in max) || value + 0 > max[key] + 0) max[key] = value
      }
      END { for (k in max) print k "\t" max[k] }' \
  | LC_ALL=C sort
}

# compare BASE CUR: prints one line per difference and exits 1 on a
# regression (new or grown), 2 when only improvements are unrecorded,
# 0 when the two agree.
compare() {
  awk -F'\t' '
    FILENAME == ARGV[1] { if ($0 !~ /^#/ && NF >= 4) base[$1 FS $2 FS $3] = $4; next }
    {
      key = $1 FS $2 FS $3; cur[key] = $4
      if (!(key in base)) { print "NEW    " $0; bad = 1 }
      else if ($4 + 0 > base[key] + 0) { print "GREW   " $0 " (baseline " base[key] ")"; bad = 1 }
      else if ($4 + 0 < base[key] + 0) { print "SHRANK " $0 " (baseline " base[key] ")"; stale = 1 }
    }
    END {
      for (k in base) if (!(k in cur)) { print "GONE   " k "\t" base[k]; stale = 1 }
      exit (bad ? 1 : (stale ? 2 : 0))
    }' "$1" "$2"
}

write_baseline() {
  local count
  count=$(wc -l < "$1" | tr -d ' ')
  {
    # REUSE-IgnoreStart (these tags belong to the generated file)
    printf '# SPDX-FileCopyrightText: 2026 Noyalib\n'
    printf '# SPDX-License-Identifier: MIT OR Apache-2.0\n'
    # REUSE-IgnoreEnd
    printf '#\n'
    printf '# Complexity baseline: every function over a ceiling, with its measured value.\n'
    printf '# Generated by scripts/complexity-baseline.sh --update; regenerate only to record\n'
    printf '# an improvement. The script refuses to record a regression.\n'
    printf '# ceilings: too_many_lines 60, cognitive_complexity 15 (scripts/complexity/clippy.toml)\n'
    printf '# measured with: %s\n' "$(cargo clippy --version 2>/dev/null || echo 'clippy (version unavailable)')"
    printf '# entries: %s\n' "$count"
    printf 'lint\tfile\tfunction\tvalue\n'
    cat "$1"
  } > "$BASELINE"
}

measure | rows > "$WORK/current.tsv"
: > "$WORK/base.tsv"
if [ -f "$BASELINE" ]; then
  grep -v '^lint	file' "$BASELINE" > "$WORK/base.tsv" || :
fi

status=0
compare "$WORK/base.tsv" "$WORK/current.tsv" > "$WORK/diff.txt" || status=$?
# A first --update has nothing to regress against: it records the tree.
[ "$MODE" = update ] && [ ! -f "$BASELINE" ] && status=0

case "$MODE:$status" in
  check:0)
    printf 'complexity: %s functions over a ceiling, all recorded in %s\n' \
      "$(wc -l < "$WORK/current.tsv" | tr -d ' ')" "${BASELINE#"$PWD"/}"
    ;;
  check:1)
    echo "complexity: regression against ${BASELINE#"$PWD"/}" >&2
    cat "$WORK/diff.txt" >&2
    echo "Bring the function under the ceiling; the baseline only shrinks." >&2
    ;;
  check:2)
    echo "complexity: the tree improved but ${BASELINE#"$PWD"/} still lists the old state" >&2
    cat "$WORK/diff.txt" >&2
    echo "Run scripts/complexity-baseline.sh --update to record it." >&2
    ;;
  update:1)
    echo "complexity: refusing to record a regression" >&2
    cat "$WORK/diff.txt" >&2
    ;;
  update:*)
    write_baseline "$WORK/current.tsv"
    printf 'complexity: wrote %s entries to %s\n' \
      "$(wc -l < "$WORK/current.tsv" | tr -d ' ')" "${BASELINE#"$PWD"/}"
    status=0
    ;;
esac
exit "$status"
